### ISSUE TITLE
Sporadic error: java.lang.NoClassDefFoundError: gopkg/in/bblfsh/sdk/v1/uast/generated/Node

### ISSUE THREAD

**Issue by ajnavarro** [bblfsh/client-scala#19]
Exception in thread "Executor task launch worker for task 3815" java.lang.NoClassDefFoundError: gopkg/in/bblfsh/sdk/v1/uast/generated/Node
        at org.bblfsh.client.libuast.Libuast.filter(Native Method)
        at org.bblfsh.client.BblfshClient.filter(BblfshClient.scala:34)
        at tech.sourced.api.udf.QueryXPathUDF$$anonfun$queryXPath$2.apply(QueryXPathUDF.scala:46)
        at tech.sourced.api.udf.QueryXPathUDF$$anonfun$queryXPath$2.apply(QueryXPathUDF.scala:44)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at tech.sourced.api.udf.QueryXPathUDF$.queryXPath(QueryXPathUDF.scala:44)
        at tech.sourced.api.udf.QueryXPathUDF$$anonfun$apply$1.apply(QueryXPathUDF.scala:25)
        at tech.sourced.api.udf.QueryXPathUDF$$anonfun$apply$1.apply(QueryXPathUDF.scala:24)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:234)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:228)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by abeaumont** [comment]
Can you provide some additional insight? Which query causes the problem, how to reproduce it, etc.?

**Comment by juanjux** [comment]
Nope. This one isn't still fixed. But at least now is consistently reproducible.

**Comment by juanjux** [comment]
Fixed by #23.
