### ISSUE TITLE
Fail to run latest release 1.3.4

### ISSUE THREAD

**Issue by warenlg** [bblfsh/client-scala#43]
Follow the steps from https://github.com/bblfsh/client-scala#usage

step to reproduce 
  - `wget http://central.maven.org/maven2/org/bblfsh/bblfsh-client/1.3.4/bblfsh-client-1.3.4.jar`
  - `java -jar ./bblfsh-client-1.3.4.jar --host 0.0.0.0 -f src/test/resources/python_file.py`

Expected output
printed uast according to https://github.com/bblfsh/client-scala#usage

Actual output

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Function0
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: scala.Function0
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by juanjux** [comment]
The Maven JAR is not a fat-JAR so it doesn't have all dependencies (the sbt authors strongly [discourage it](https://github.com/sbt/sbt-assembly#publishing-not-recommended)). 

If you need it to be so please open a feature request.
