### ISSUE TITLE
Expose method for gRPC connection termination

### ISSUE THREAD

**Issue by bzz** [bblfsh/client-scala#71]
Right now `BblfshClient` manages the connection creation, but it relies on GC to shut the connection down.

It would be nice to expose something gRCP's channel `.shutdownNow()` method to allow clients to for more fine-grained resource control and to avoid this message on a process termination (i.e in tests):

```
ERROR 00:53:24,580 io.grpc.internal.ManagedChannelImpl$ManagedChannelReference (ManagedChannelImpl.java:1236) - *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-1 for target 127.0.0.1:9432 was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and awaitTermination().
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelImpl$ManagedChannelReference.<init>(ManagedChannelImpl.java:1185)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:504)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:369)
	at org.bblfsh.client.BblfshClient.<init>(BblfshClient.scala:19)
	at org.bblfsh.client.BblfshClient$.apply(BblfshClient.scala:81)
```

Will be happy to provide a patch, in case there is a consensus of usefulness of such method.

**Comment by bzz** [comment]
@dennwc @juanjux what do you guys think?

**Comment by juanjux** [comment]
I agree that it would be useful and patches are welcome, if not I could do it as soon as I finish my current task (tomorrow probably).
